Django
mezidia/song-helper pull request #16
Opened 2021-02-22 19:12 UTC by fhrr-sht

2021-03-01 08:08 UTC, mezgoodle commented
[Template](https://getbootstrap.com/docs/5.0/examples/sign-in/) needs to set

2021-03-07 13:36 UTC, mezgoodle approved these changes

2021-03-12 10:12 UTC, mezgoodle commented on server/mesite/models.py
> +    artist = models.CharField('Artists', blank=False, max_length=20)
```suggestion
    artists = models.CharField('Artists', blank=False, max_length=20)
```

2021-03-12 10:12 UTC, mezgoodle commented on server/mesite/models.py
> +    key = models.IntegerField()
```suggestion
    key = models.FloatField()
```

2021-03-12 10:13 UTC, mezgoodle commented on server/mesite/models.py
> +    time_signature = models.IntegerField()
```suggestion
    time_signature = models.FloatField()
```

2021-03-12 10:13 UTC, mezgoodle requested changes
Fields changed

2021-03-12 11:28 UTC, mezgoodle commented on server/mesite/tests.py
> +            artist='Test artist',
```suggestion
            artists='Test artist',
```

2021-03-12 11:29 UTC, mezgoodle requested changes

2021-03-12 11:29 UTC, mezgoodle commented on server/mesite/tests.py
> +            key=3123,
```suggestion
            key=3123.0,
```

2021-03-12 11:29 UTC, mezgoodle commented on server/mesite/tests.py
> +            time_signature=0,
```suggestion
            time_signature=0.0,
```

2021-03-12 11:57 UTC, mezgoodle commented on server/mesite/tests.py
> +        self.assertIsInstance(song.energy, float)
```suggestion

```

2021-03-12 11:58 UTC, mezgoodle commented on server/mesite/tests.py
> +        self.assertIsInstance(song.key, int)
```suggestion

```

2021-03-12 11:59 UTC, mezgoodle commented on server/mesite/tests.py
> +        self.assertIsInstance(song.key, int)
```suggestion
        self.assertIsInstance(song.key, float)
```

2021-03-12 15:08 UTC, mezgoodle approved these changes

2021-04-15 14:51 UTC, VsIG-official approved these changes
вот е грейт ворк Ю хев зєр

2021-04-15 14:51 UTC, merged