Parser
mezidia/song-helper pull request #26
Opened 2021-03-16 17:04 UTC by mezgoodle

2021-03-17 07:42 UTC, mezgoodle commented
CI **will not work** for this _branch_, due to [workflow](https://github.com/mezidia/song-helper/blob/django/.github/workflows/django.yml) in _django_ branch. But I ran tests locally and give you result below:
![image](https://user-images.githubusercontent.com/41520940/111431003-e0236600-8703-11eb-94cc-8ac8bd64250f.png)

2021-03-21 07:37 UTC, Dmytrenko-Roman commented on server/mesite/tests.py
> +        params = {'limit': 1}
```suggestion
        params1 = {'limit': 1}
```

2021-03-21 07:40 UTC, Dmytrenko-Roman requested changes

2021-03-21 07:40 UTC, Dmytrenko-Roman commented on server/mesite/tests.py
> +        params_1 = {'limit': 3}
```suggestion
        params2 = {'limit': 3}
```

2021-03-21 07:40 UTC, Dmytrenko-Roman commented on server/mesite/tests.py
> +        result = search_youtube(str_to_search, params)
Rewrite all variables. Example: result & result_1 to result1 & result2.

2021-03-21 07:40 UTC, Dmytrenko-Roman commented on server/requirements.txt
> +youtube-search-python==1.4.2
where is nodejs?

2021-03-21 07:56 UTC, Dmytrenko-Roman approved these changes

2021-04-07 10:20 UTC, mezgoodle commented on server/requirements.txt
> +youtube-search-python==1.4.2
On my computer

2021-04-14 13:46 UTC, merged