🐦 Deleted .vs & .vscode files | Updated README 🐦 / Issue #37
mezidia/song-helper pull request #50
Opened 2021-04-23 13:40 UTC by Dmytrenko-Roman

2021-04-23 13:41 UTC, VsIG-official approved these changes

2021-04-23 19:05 UTC, mezgoodle requested changes
Please change this content:

- [x] on [line 15](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L15) change `about AI on Python` to `about project on Python`
- [x] on [line 65](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L65) change `We get a description of the mood in _two different ways_: through a **bot** (Telegram) in the form of a text message and through a form on the **site** (Django). Next, the text is converted to a vector, compared with the song vectors in the database, and the result is returned as a song reference (in both cases).` to `We get a description of the mood in  _different ways_: through a **bot** (Telegram, Discord) in the form of a text message, through a form on the **site** (Django) , through a form on the **mobile app** (Kivy App). Next, the text is converted to a vector, compared with the mood vectors, getting a random song with this mood from databae and the result is returned as a song reference (in each cases).`
- [x] on [line 66](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L66) change `The site will have only one page with a form for entering a description. No other pages are planned yet.` to `The site will have one more page with a form for entering a song id from _Spotify_. This is for making database bigger. Also you can do it from bots in Telegram and Discord`
- [ ] Delete [line 71](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L71) and replace it with the next labels:  
  - `[![Docker](https://github.com/mezidia/song-helper/actions/workflows/docker-publish.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/docker-publish.yml)`
  - `[![Docker Image CI](https://github.com/mezidia/song-helper/actions/workflows/docker-image.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/docker-image.yml)`

- [ ] on [line 94](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L94) add the next libraries:
  - `- [Kivy](https://kivy.org/#home)`
  - `- [pandas](https://pandas.pydata.org/)`
  - `- [discord.py](https://discordpy.readthedocs.io/en/stable/)`

2021-04-24 06:35 UTC, Dmytrenko-Roman commented
> Please change this content:
> 
> * [x]  on [line 15](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L15) change `about AI on Python` to `about project on Python`
> * [x]  on [line 65](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L65) change `We get a description of the mood in _two different ways_: through a **bot** (Telegram) in the form of a text message and through a form on the **site** (Django). Next, the text is converted to a vector, compared with the song vectors in the database, and the result is returned as a song reference (in both cases).` to `We get a description of the mood in  _different ways_: through a **bot** (Telegram, Discord) in the form of a text message, through a form on the **site** (Django) , through a form on the **mobile app** (Kivy App). Next, the text is converted to a vector, compared with the mood vectors, getting a random song with this mood from databae and the result is returned as a song reference (in each cases).`
> * [x]  on [line 66](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L66) change `The site will have only one page with a form for entering a description. No other pages are planned yet.` to `The site will have one more page with a form for entering a song id from _Spotify_. This is for making database bigger. Also you can do it from bots in Telegram and Discord`
> * [x]  Delete [line 71](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L71) and replace it with the next labels:
>   
>   * `[![Docker](https://github.com/mezidia/song-helper/actions/workflows/docker-publish.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/docker-publish.yml)`
>   * `[![Docker Image CI](https://github.com/mezidia/song-helper/actions/workflows/docker-image.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/docker-image.yml)`
> * [x]  on [line 94](https://github.com/mezidia/song-helper/blob/Delete-files/README.md#L94) add the next libraries:
>   
>   * `- [Kivy](https://kivy.org/#home)`
>   * `- [pandas](https://pandas.pydata.org/)`
>   * `- [discord.py](https://discordpy.readthedocs.io/en/stable/)`

Done! 😊

2021-04-24 07:25 UTC, mezgoodle commented on README.md
> +- We get a description of the mood in _two different ways_: through a **bot** (Telegram) in the form of a text message and through a form on the **site** (Django). Next, the text is converted to a ve
```suggestion
- We get a description of the mood in _different ways_: through a **bot** (Telegram, Discord) in the form of a text message, through a form on the **site** (Django) , through a form on the **mobile app** (Kivy App). Next, the text is converted to a vector, compared with the mood vectors, getting a random song with this mood from databae and the result is returned as a song reference (in each cases).
```

2021-04-24 07:25 UTC, mezgoodle commented on README.md
> +- The site will have only one page with a form for entering a description. No other pages are planned yet. to The site will have one more page with a form for entering a song id from _Spotify_. This
```suggestion
- The site will have one more page with a form for entering a song id from _Spotify_. This is for making database bigger. Also you can do it from bots in Telegram and Discord.
```

2021-04-24 07:26 UTC, mezgoodle requested changes
You forgot to delete old text

2021-04-24 08:53 UTC, Dmytrenko-Roman commented
> You forgot to delete old text

Done! 😅

2021-04-24 14:14 UTC, mezgoodle commented
> > You forgot to delete old text
> 
> Done! 😅

![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)

2021-04-24 16:59 UTC, mezgoodle approved these changes

2021-04-24 16:59 UTC, merged